config/routes.rb
BeerApp::Application.routes.draw do

  resources :recipes
  resources :fermentables
  resources :hops
  resources :recipes do
    resources :hop_manifests, only: [:index]
    resources :fermentable_manifests, only: [:index]
  end
  resources :hop_manifests, only: [:create,:update,:destroy]
  resources :fermentable_manifests, only: [:create,:update,:destroy]
  
  root to: 'recipes#index'

end

app/models/hop.rb
class Hop < ActiveRecord::Base
  attr_accessible :name, :unit_price, :weight_unit, :description
end

app/controllers/hops_controller.rb
class HopsController < ApplicationController
  def index
    @hops = Hop.all
  end

  def show
    @hop = Hop.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @hop}
    end
  end

  def new
    @hop = Hop.new
  end

  def create
    @hop = Hop.new(params[:hop])

    if @hop.save
      redirect_to hops_path
    end
  end

  def edit
    @hop = Hop.find(params[:id])
  end

  def update
    @hop = Hop.find(params[:id])
    if @hop.update_attributes(params[:hop])
      redirect_to hops_path
    else
      render 'edit'
    end
  end

  def destroy
    @hop = Hop.find(params[:id]).destroy
    redirect_to hops_path
  end
end

app/helpers/hops_helper.rb
module HopsHelper
end

app/views/hops/_fields.html.erb
<%= f.label :name, 'Hop Name' %>
<%= f.text_field :name %>
<%= f.label :description, 'Hop description' %>
<%= f.text_field :description %>

app/views/hops/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for @hop do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Update" %>
    <% end %>
  </div>
</div>

app/views/hops/index.html.erb
<h1>All your hops are belong to us</h1>
<div class="row">
  <div class= "span6 offset3">
    <%= link_to "New", new_hop_path %> <br />
    <input type="text" id= "auto_complete" class="span3" style="margin: 0 auto;"> 
    <%= javascript_tag "var autocomplete_items = #{ @hops.map(&:name).to_json };" %>
    <script type="text/javascript">
      jQuery(document).ready(function() {
          $('#auto_complete').typeahead({source: autocomplete_items});
          });
        </script>
        <dl class="dl-horizontal">
          <% @hops.each do |hop| %>
            <dt><%=link_to hop.name, edit_hop_path(hop), class: "table-title"%> </dt> <dd><%= hop.description %></dd>
          <% end %>
        </dl>
      </div>
    </div>

    *Most hop descriptions graciously taken from BYO magazine.

app/views/hops/new.html.erb
<h1>Hops#new</h1>
<p>Find me in app/views/hops/new.html.erb</p>

app/views/hops/show.html.erb
<h1>Hops#show</h1>
<p>Find me in app/views/hops/show.html.erb</p>