config/routes.rb
BeerApp::Application.routes.draw do

  resources :recipes
  resources :fermentables
  resources :hops
  resources :recipes do
    resources :hop_manifests, only: [:index]
    resources :fermentable_manifests, only: [:index]
  end
  resources :hop_manifests, only: [:create,:update,:destroy]
  resources :fermentable_manifests, only: [:create,:update,:destroy]
  
  root to: 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :fg, :ibu, :name, :og, :style_id, :user_id, :fermentable_manifests_attributes, :hop_manifests_attributes, :final_volume, :description

  validates :final_volume, presence: true, :numericality => { greater_than: 0 }
  validates :name, :description, presence: true
  has_many :hop_manifests, dependent: :destroy
  has_many :fermentable_manifests, dependent: :destroy
  has_many :hops, through: :hop_manifests
  has_many :fermentables, through: :fermentable_manifests
  accepts_nested_attributes_for :fermentable_manifests, :reject_if => lambda { |a| a[:amount].blank? }
  accepts_nested_attributes_for :hop_manifests, :reject_if => lambda { |a| a[:aau].blank? or a[:boil_time].blank? }

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :update_recipe_og, :only => :show
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.ibu = 0
    if @recipe.save
      redirect_to @recipe
    else
      render action: 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      if params[:update_type]
        render json: @recipe
      else
        redirect_to @recipe, :notice =>"Successfully updated"
      end
    else
      render action: 'edit'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @new_hop = @recipe.hop_manifests.build
    @new_ferm = @recipe.fermentable_manifests.build

    respond_to do |format|
      format.html
      format.json {render json: @recipe}
    end
  end

  def index
    @recipes = Recipe.all
  end

  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    redirect_to recipes_path
  end
  private
    def update_recipe_og
      @recipe = Recipe.find(params[:id])
      total_points = 0
      @recipe.fermentable_manifests.each do |ferm|
        ferm_points = ferm.amount * ferm.fermentable.ppg / 16 
        total_points = total_points + ferm_points
      end
      new_og = total_points / (1000 * @recipe.final_volume) + 1
      new_og = new_og.round(3)
      @recipe.og = new_og
      @recipe.save
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_fields.html.slim
=simple_form_for @recipe do |f|
  =f.input :name
  =f.input :description
  =f.input :final_volume, placeholder: "Gallons"
  =f.input :fg, label: "Target final gravity"
  =f.button :submit

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.slim
= link_to 'Recipe info', @recipe

=render :partial => 'fields'

= link_to 'Delete', @recipe, method: :delete, class: 'btn'

app/views/recipes/index.html.slim
h1 Recipes
.row
  .span2 = link_to raw('<i class="icon-plus"></i>'), new_recipe_path, class: "btn"
.row
  .span10
      - @recipes.each do |recipe|
        .row
         .span2=link_to "#{recipe.name}", recipe
         .span5=recipe.description
         .span1 OG: #{recipe.og}
         .span1 IBU: #{recipe.ibu}

app/views/recipes/new.html.slim
= link_to 'Recipes', recipes_path

=render :partial => 'fields'

app/views/recipes/show.html.slim
-content_for :head do
  = javascript_include_tag 'recipe_show.js'
.row
  .span6.recipe-info#recipe-header data-url=recipe_path(@recipe.id)
    h1 = @recipe.name
    h2 = @recipe.description
  .span4
    p.gravity_label
      | OG 
      span#recipe_og =@recipe.og
      span.label.label-default Lock
    p.gravity_label
      | FG 
      span#recipe_fg =@recipe.fg
    p.gravity_label
      | IBU 
      span#recipe_ibu =@recipe.ibu
    p.gravity_label
      span.gravity_label#recipe_volume =@recipe.final_volume
      |  Gallons
    =link_to 'Edit recipe settings', edit_recipe_path(@recipe.id)
.row
  .span5
    h3 Fermentables
  .span3
    span.small.pull-right Assume 70% mash efficiency
.row
  .span8
    table.table#fermentables_table
      tr
        th 
        th Name
        th PPG
        th Oz
        th Points OG
        th %OG
      - @recipe.fermentable_manifests.each do |ferm|
        -if !ferm.fermentable.nil?
          tr.fermentable_entry id="#{ferm.id}" data-url=fermentable_manifest_url(ferm.id)
            td =link_to "remove", ferm, method: "delete", remote: true, class: "remove-fermentable"
            td.ferm-name data-title="#{ferm.fermentable.ppg} PPG" = ferm.fermentable.name
            td.ppg = ferm.fermentable.ppg
            td.amount = ferm.amount
            td.points_og
            td.percent_og

    =simple_form_for @new_ferm do |f|
      div.control-group
        =f.collection_select :fermentable_id, Fermentable.all, :id, :name
        =f.text_field :amount, class: 'input-small' , placeholder: "ounces"
        span id="ferm_type_buttons" class="btn-group" data-toggle="buttons-radio"
          button id="oz" type="button" class="btn active"oz 
          button id="og" type="button" class="btn"pts OG
        =f.hidden_field :recipe_id
        =hidden_field_tag 'ppg' 
        =f.button :submit, "Add"
        javascript:
          $("span#ferm_type_buttons:first").button('toggle');
          $("td.ferm-name").tooltip();
          

.row
  .span8
    h3 Hops
    table.table#hops_table
      tr
        th
        th Name
        th AAU
        th Boil Time
        th IBU
      - @recipe.hop_manifests.each do |hm|
        -if !hm.hop.nil?
          tr.hop_entry
            td =link_to "remove", hm, :method => :delete, remote: true, class: "remove-hop"
            td.name= hm.hop.name
            td.aau = hm.aau
            td.boil_time = hm.boil_time
            td.ibu
    =simple_form_for @new_hop do |h|
        div.control-group
          =h.hidden_field :recipe_id
          =h.collection_select :hop_id, Hop.all, :id, :name
          =h.text_field :aau, :class => 'input-mini', placeholder: "AAUs"
          span id="hop_type_buttons" class="btn-group" data-toggle="buttons-radio"
            button id="aau" type="button" class="btn active"AAU 
            button id="ibu" type="button" class="btn"IBU
          =h.text_field :boil_time,  :class => 'input-mini', placeholder: "minutes"
          span boil time 
          =h.button :submit, "Add"

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>