config/routes.rb
BeerApp::Application.routes.draw do

  resources :recipes
  resources :fermentables
  resources :hops
  resources :recipes do
    resources :hop_manifests, only: [:index]
    resources :fermentable_manifests, only: [:index]
  end
  resources :hop_manifests, only: [:create,:update,:destroy]
  resources :fermentable_manifests, only: [:create,:update,:destroy]
  
  root to: 'recipes#index'

end

app/controllers/fermentables_controller.rb
class FermentablesController < ApplicationController
  def index
    @fermentables = Fermentable.all
  end

  def show
    @fermentable = Fermentable.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @fermentable}
    end
  end

  def edit
    @fermentable = Fermentable.find(params[:id])
  end

  def update
    @fermentable = Fermentable.find(params[:id])
    if @fermentable.update_attributes(params[:fermentable])
      redirect_to fermentables_path
    else
      render 'edit'
    end
  end
  def destroy
    Fermentable.find(params[:id]).destroy
    redirect_to fermentables_path
  end

  def new
    @fermentable = Fermentable.new
  end

  def create
    @fermentable = Fermentable.new(params[:fermentable])
    if @fermentable.save
      redirect_to fermentables_path
    else
      render 'new'
    end
  end
end

app/helpers/fermentables_helper.rb
module FermentablesHelper
end

app/views/fermentables/_fields.html.erb
<%= f.label :name, 'Name' %>
<%= f.text_field :name %>

<%= f.label :ppg, 'PPG' %>
<%= f.text_field :ppg %>

app/views/fermentables/edit.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for ( @fermentable ) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Update Ingredient", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= link_to "Delete", @fermentable, method: :delete%>
  </div>
</div>

app/views/fermentables/index.html.erb
<h1>Fermentables</h1>

<div class="row">
  <div class="span8 offset4">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th><th>Maximum Yield</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to "New", new_fermentable_path %></td><td></td>
        </tr>
        <% @fermentables.each do |ferm| %>
          <tr>
            <td class="table-title"><%=link_to ferm.name, edit_fermentable_path(ferm), class: "table-title" %></td><td> <%= ferm.ppg%> PPG</td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/fermentables/new.html.erb
<h1>Fermentables#new</h1>
<p>Find me in app/views/fermentables/new.html.erb</p>

app/views/fermentables/show.html.erb
<h1>Fermentables#show</h1>
<p>Find me in app/views/fermentables/show.html.erb</p>